config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quacks
  root :to => 'quacks#index'
end

app/models/quack.rb
class Quack < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :quacks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quacks_controller.rb
class QuacksController < ApplicationController
  def index
    @quacks = Quack.all.order('created_at DESC')
  end
  def new
    @quack = Quack.new
  end
  def create
    @quack = Quack.new(quack_params)
    @quack.user = current_user
    if @quack.save
      respond_to do |format|
        format.html { redirect_to quacks_path }
        format.js
      end
      flash[:notice] = "Quack successful!"
    else
      flash[:alert] = "Failure. Please retry."
    end
  end
  def destroy
    @quack = Quack.find(params[:id])
    @quack.destroy
    respond_to do |format|
      format.html { redirect_to quacks_path }
      format.js
    end
    flash[:alert] = "Quack deleted"

  end


# PRIVATE PRIVATE PRIVATE PRIVATE PRIVATE PRIVATE PRIVATE PRIVATE PRIVATE
private
  def quack_params
    params.require(:quack).permit(:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quacker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar_header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Quacker</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><a><%= current_user.email %></a></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to "Sign up", new_user_registration_path %> </li>
            <li> <%= link_to "Log In", new_user_session_path %> </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/quacks/_form.html.erb
<div class="panel panel-primary" id="form_box">
  <div class="panel-heading">
    <h3 class="panel-title">New Quack</h3>
  </div>
  <div class="panel-body">
    <%= bootstrap_form_for @quack, remote: true do |f| %>
      <%= f.text_area :body %>
      <%= f.submit "Quack", class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/quacks/_quack.html.erb
<div class="panel panel-primary" id="quack_panel_<%= quack.id %>">
  <div class="panel-heading">
    <h3 class="panel-title"><%= quack.user.email %><small class="pull-right"><%= distance_of_time_in_words_to_now(quack.created_at) %> ago</small></h3>
  </div>
  <div class="panel-body">
  <%= quack.body %>
  <%= link_to("Delete", quack_path(quack),:data => {:confirm => "Are you sure?", :method => "delete"}, remote: true, class: "btn btn-xs pull-right") %>
  </div>
</div>

app/views/quacks/create.js.erb
$('#form_box').remove();
$('#new_link').show();
$('#quack-list').prepend('<%= j render @quack %>');

app/views/quacks/destroy.js.erb
$('#quack_panel_<%= @quack.id %>').remove();

app/views/quacks/index.html.erb
<div class="row">
  <div class="col-sm-2">
    <% if current_user %>
      <%= link_to "Quack", new_quack_path, id: 'new_link', remote: true, class: "btn btn-success" %>
    <% else %>
      <h5>You must login in order to quack.</h5>
    <% end %>
  </div>
  <div class="col-sm-8" id="quack-list">
    <div>
      <% if @quacks.any? %>
      <%= render partial: "quack", collection: @quacks %>


        
      <% else %>
        Get quacking!
      <% end %>
    </div>
  </div>
  <div class="col-sm-2"></div>

</div>

app/views/quacks/new.html.erb
<%= render 'form' %>

app/views/quacks/new.js.erb
$('#new_link').hide();
$('#quack-list').prepend('<%= j render('form') %>');